repos:
-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.6.0
    hooks:
    - id: check-added-large-files
    - id: check-merge-conflict
    - id: check-yaml
    - id: detect-private-key
    - id: end-of-file-fixer
    - id: trailing-whitespace

-   repo: https://github.com/astral-sh/ruff-pre-commit
    rev: "v0.6.2"
    hooks:
      - id: ruff
        args: ["--fix", "--show-fixes"]
        exclude: 4-tools/is_this_pep8.py
      - id: ruff-format
        exclude: 4-tools/is_this_pep8.py

- repo: https://github.com/codespell-project/codespell
  rev: "v2.3.0"
  hooks:
    - id: codespell
      # Here are the args to ignore words: ["-L", "sur,nd"]
      args: ["--write-changes", "-L", "inout"]

  # This hook strips .ipynb files before commiting
- repo: https://github.com/kynan/nbstripout
  rev: 0.7.1
  hooks:
    - id: nbstripout

- repo: local
  hooks:
    - id: remove-unreferenced-imgs
      name: remove-unreferenced-imgs
      entry: sh -c 'find imgs/ -type f \( -exec git grep --quiet {} \; -o -exec git rm {} \; \)'
      language: system
      always_run: true
      pass_filenames: false
