theme: jekyll-theme-cayman
title: LundPython
description: Website for Python programming @ Lund Observatory
download_url: "https://mikkolad.github.io/lundpython/downloads"
schedule_url: "https://mikkolad.github.io/lundpython/schedule"
guide_url: "https://mikkolad.github.io/lundpython/guide"
remote_theme: pages-themes/cayman@v0.2.0
plugins:
- jekyll-remote-theme
