theme: jekyll-theme-cayman
title: LundPython
description: Here you will find the course material for the python programming course @ Lund Observatory
download_url: "https://mikkolad.github.io/CourseMaterials/downloads"
schedule_url: "https://mikkolad.github.io/CourseMaterials/schedule"
guide_url: "https://mikkolad.github.io/CourseMaterials/guide"
