line-length = 90
indent-width = 4

[format]
# Use same settings as Black.
quote-style = "double"
indent-style = "space"
docstring-code-format = true
skip-magic-trailing-comma = false
line-ending = "auto"

[lint]
select = [
    # pycodestyle
    "E",
    # pyupgrade
    "UP",
    # flake8-bugbear
    "B",
    # NumPy-specific rules
    "NPY",
]

[lint.pydocstyle]
convention = "numpy"

[lint.flake8-annotations]
ignore-fully-untyped = true # Codebase has no types
