line-length = 90
indent-width = 4

[format]
# Use same settings as Black.
quote-style = "double"
indent-style = "space"
docstring-code-format = true
skip-magic-trailing-comma = false
line-ending = "auto"

[lint]
select = [
    # pycodestyle
    "E", "W",
    # pyupgrade
    "UP",
    # flake8-bandit
    "S",
    # flake8-bugbear
    "B",
    # flake8-commas
    "COM",
    # flake8-comprehensions
    "C4",
    # flake8-pie
    "PIE",
    # flake8-use-pathlib
    "PTH",
    # NumPy-specific rules
    "NPY",
]
ignore = [
    # Recommended for compatibility with formatter
    "COM812",
]

[lint.pydocstyle]
convention = "numpy"

[lint.flake8-annotations]
ignore-fully-untyped = true # Codebase has no types
