line-length = 90
target-version = "py312"

[format]
# Use default settings.
docstring-code-format = true  # This is disabled by default but will become opt-out in the future.
exclude = ["4-tools/is_this_pep8.py"]

[lint]
select = [
    # pycodestyle
    "E", "W",
    # pyupgrade
    "UP",
    # flake8-bandit
    "S",
    # flake8-bugbear
    "B",
    # flake8-commas
    "COM",
    # flake8-comprehensions
    "C4",
    # flake8-pie
    "PIE",
    # flake8-use-pathlib
    "PTH",
    # NumPy-specific rules
    "NPY",
]
ignore = [
    # Recommended for compatibility with formatter
    "COM812",
]
