line-length = 88
indent-width = 4

[format]
# Use same settings as Black.
quote-style = "double"
indent-style = "space"
docstring-code-format = true
skip-magic-trailing-comma = false
line-ending = "auto"


[lint]
select = ["ALL"]
ignore = [
    "INP001",   # implicit-namespace-package
    "COM812",   # TrailingCommaMissing
    "COM819",   # TrailingCommaProhibited
    "ISC001",   # single-line-implicit-string-concatenation
    "T201",     # print
    "D103",     # undocumented-public-function
]

[lint.pydocstyle]
convention = "numpy"

[lint.flake8-annotations]
ignore-fully-untyped = true # Codebase has no types
