<img src="https://lund-observatory-teaching.github.io/lundpython/imgs/front_1.jpeg" width="1400">

<h1><center> The course </center></h1>

#### Prior lecturer - Simon and Eero 
<br>

### This lecture is a mini-series companion to: 

**ASTM28**: Dynamical Astronomy

**ASTM29**: Statistical tools in astrophysics
<br>
<br>

**Lecture 1**: Introduction to Python - Today <br>
**Lecture 2**: Numpy - 3 Sep 09:15 - 12:00 <br>
**Lecture 3**: Plotting - 4 Sep 13:15 - 16:00 <br>
**Lecture 4**: Project 1 - 8 Sep 13:15 - 16:00 <br>

<h1><center> Course website </center></h1>

To download all lecture files and see the schedule, please visit:

[lund-observatory-teaching.github.io/lundpython/](https://lund-observatory-teaching.github.io/lundpython/)


Each lecture contains (as notebooks)
- Manual 
- Exercises
- Presentation

---

# Go to www.menti.com and enter code: xxxx xxxx

<h1><center> Writing Python </center></h1>

The easiest way to get started is to install Anaconda (see guide on webpage). It includes Python, Jupyter, NumPy, SciPy and Matplotlib.

If you prefer another installation method, the NumPy installation guide has instructions for different operating systems:

[https://numpy.org/install/](https://numpy.org/install/#python-numpy-install-guide)

It covers all cases with different operating systems and user experience levels. 

There are two common programs you might want to use for writing Python:

### [Jupyter Notebook](https://jupyter.org/) 

##### You write and run code in separate cells, mixed with text, equations, and plots. Great for data analysis.

> The Jupyter Notebook is an open-source web application that allows you to create and share documents that contain live code, equations, visualizations and narrative text. Uses include: data cleaning and transformation, numerical simulation, statistical modeling, data visualization, machine learning, and much more.

#### See Example

### [Spyder](https://www.spyder-ide.org/)

##### Looks more like a traditional programming program/IDE. You usually write a Python script (.py) and run it.

> Spyder is a powerful scientific environment written in Python, for Python, and designed by and for scientists, engineers and data analysts. It features a unique combination of the advanced editing, analysis, debugging, and profiling functionality of a comprehensive development tool with the data exploration, interactive execution, deep inspection, and beautiful visualization capabilities of a scientific package.


# Let's get started with a brief introduction!
## Hello, World!

Let's make Python say `Hello, World!`

In [41]:
print("Hello, World!")

Hello, World!


In [42]:
print('Hello!!!')

Hello!!!


And now we try something more complicated.

In [45]:
a = 4
b = 5

print(a+b)

print(f"The sum of {a=} and {b=} is {a+b = }.") #f lets you put variable values into text

9
The sum of a=4 and b=5 is a+b = 9.


# If statement 

An if statement lets Python make a decision. The code runs only when the condition is true.

In [48]:
x=6

if x > 5:
    print("x is bigger than 5")

x is bigger than 5


# For loops and While loops 

There are two basic types of loops in Python: for loops and while loops.

A for loop is useful when we know how many times we want to repeat something.

In [49]:
for i in range(5):
    print(i)

0
1
2
3
4


A while loop keeps repeating as long as a condition is true.

In [50]:
i = 0

while i < 5:
    print(i)
    i = i + 1

0
1
2
3
4


# Functions

A function is a reusable piece of code.

It can take input, do something with it, and return an output.

In [51]:
def add(a, b):
    return a + b

add(2, 3)
add(5,5)

10

# Built-in types

Python has different types of values. They may look similar, but Python treats them as different things.

Some of the Python built-in types you will use a lot are:

In [4]:
for elem in (5, 5.0, "5", [5], (5,)):
    print(f"{elem} is {type(elem).__name__}")

5 is int
5.0 is float
5 is str
[5] is list
(5,) is tuple


## Booleans

There are two Boolean values: `True` and `False`.

Booleans are used when Python checks whether something is true or false.

In [53]:
print(2 > 3)   # True or False?

False


Other values can also be treated as `True` or `False`:
- Values treated as `True` are called **truthy**.
- Values treated as `False` are called **falsy**.

In [61]:
for elem in (2, -1, "", 0.0, [], [0], (), ((),)):
    if elem:
        print(f"{elem} is truthy")
    else:
        print(f"{elem} is falsy")

2 is truthy
-1 is truthy
 is falsy
0.0 is falsy
[] is falsy
[0] is truthy
() is falsy
((),) is truthy


Numerical representations of 0 and empty containers are falsy. But `numpy` arrays are an exception!

## Sequences

A sequence is an ordered collection of elements.
We can access elements using an index.

In [62]:
numbers = [10, 20, 30, 40]

print(numbers[0])
print(numbers[1])
print(numbers[-1])

10
20
40


In [31]:
for seq in ([0, 1], (2, 3), range(5), "Hello, World!"):
    print(
        f'The {type(seq).__name__} "{seq}" starts with {seq[0]} and ends with {seq[-1]}',
    )

The list "[0, 1]" starts with 0 and ends with 1
The tuple "(2, 3)" starts with 2 and ends with 3
The range "range(0, 5)" starts with 0 and ends with 4
The str "Hello, World!" starts with H and ends with !


But we can loop through a sequence without using its index.

In [32]:
for letter in "word":
    print(letter)

w
o
r
d


## Let's check if a number is a prime!
And learn not to repeat ourselves

In [65]:
n = 4

# Check if n is divisible by 2
if n % 2 == 0: # % gives the remainder after division
    print(f"{n} is not prime")

# If not, check if n is divisible by 3
elif n % 3 == 0:
    print(f"{n} is not prime")

# If neither is true, n is prime
else:
    print(f"{n} is prime")

n = 5

# Check if n is divisible by 2
if n % 2 == 0:
    print(f"{n} is not prime")

# If not, check if n is divisible by 3
elif n % 3 == 0:
    print(f"{n} is not prime")

# If not, check if n is divisible by 4
elif n % 4 == 0:
    print(f"{n} is not prime")

# If none of these are true, n is prime
else:
    print(f"{n} is prime")

4 is not prime
5 is prime


But what if we want to test a large number, e.g. 23?

We can avoid repeating code if we use a while-loop.

In [67]:
n = 23
i = 2

# Try dividing n by numbers starting from 2
while i < n:

    # If the remainder is 0, n is divisible by i
    if n % i == 0:
        print(f"{n} is not prime")
        break # Stop the loop once a divisor is found

    # Try the next number
    i += 1

# If we reached n without finding a divisor, n is prime
if i == n:
    print(f"{n} is prime")

23 is prime


What about 1023?

In [73]:
n = 1023
i = 2

# Try dividing n by numbers starting from 2
while i < n:

    # If the remainder is 0, n is divisible by i
    if n % i == 0:
        print(f"{n} is not prime")
        break # Stop the loop once a divisor is found

    # Try the next number
    i += 1

# If we reached n without finding a divisor, n is prime
if i == n:
    print(f"{n} is prime")

1023 is not prime


Apparently 1023 is not a prime, let's see why.

Here we print the two numbers that multiply to give 1023

In [74]:
n = 1023
i = 2
  
# Try dividing n by numbers starting from 2
while i < n:

    # If the remainder is 0, n is divisible by i
    if n % i == 0:
        print(f"{n} is not prime, it can be written as {i}*{n//i}")
        break # Stop the loop once a divisor is found

    # Try the next number
    i += 1

# If we reached n without finding a divisor, n is prime
if i == n:
    print(f"{n} is prime")

1023 is not prime, it can be written as 3*341


What about 341, can it be factorised?

In [75]:
n = 341
i = 2

# Try dividing n by numbers starting from 2
while i < n:

    # If the remainder is 0, n is divisible by i
    if n % i == 0:
        print(f"{n} is not prime, it can be written as {i}*{n//i}")
        break # Stop the loop once a divisor is found

    # Try the next number
    i += 1

# If we reached n without finding a divisor, n is prime
if i == n:
    print(f"{n} is prime")

341 is not prime, it can be written as 11*31


Let's try an even larger number.
Inside a notebook we can use the `timeit` magic command to see how much time it takes to run.

In [76]:
%%timeit -n1 -r1

n = 433_494_437
i = 2

# Try dividing n by numbers starting from 2
while i < n:

    # If the remainder is 0, n is divisible by i
    if n % i == 0:
        print(f"{n} is not prime, it can be written as {i}*{n//i}")
        break # Stop the loop once a divisor is found

    # Try the next number
    i += 1

# If we reached n without finding a divisor, n is prime
if i == n:
    print(f"{n} is prime")

433494437 is prime
28.8 s ± 0 ns per loop (mean ± std. dev. of 1 run, 1 loop each)


The while-loop means we don't have to write out every single trial division separately, but we are still repeating code each time we test a new number.

We can save ourselves a lot of trouble if we define a function.

In [80]:
def is_prime(n):

    # Numbers below 2 are not prime
    if n < 2:
        return False

    # Start with the smallest possible divisor
    i = 2

    # Try dividing n by numbers starting from 2
    while i < n:

        # If the remainder is 0, n is divisible by i
        if n % i == 0:
            return False

        # Try the next number
        i += 1

    # If no divisor was found, n is prime
    return True

# Test the function
is_prime(47)
is_prime(3)

# Measure how long it takes for a large prime
#huge_prime = 433_494_437
#%timeit -n1 -r1 is_prime(huge_prime)

True

Let's see if we can make the function run any faster.

Instead of trying every number up to n, this version first checks if the number is even (divisible with 2), then only checks odd numbers up to the square root of n. This makes it much faster.

In [81]:
def is_prime(n):

    # Numbers below 2 are not prime
    if n < 2:
        return False

    # Check if n is divisible by 2 (except 2 itself)
    if n % 2 == 0 and n != 2:
        return False

    # Start with the first odd divisor
    i = 3

    # Check only odd divisors up to the square root of n
    while i * i <= n:

        # If the remainder is 0, n is divisible by i
        if n % i == 0:
            return False

        # Try the next odd number
        i += 2

    # If no divisor was found, n is prime
    return True


print(is_prime(huge_prime))
%timeit is_prime(huge_prime)

True
875 µs ± 4.75 µs per loop (mean ± std. dev. of 7 runs, 1,000 loops each)


# Comments

Too few comments will make your code obscure.

Too many comments will bury useful information in clutter.

Better code together with better function and variable names means fewer comments are needed.

Overly complicated and overcommented code together with bad names:

In [83]:
def norm_lst(list_):
    lst=list_.copy()           # Copy the input
    total=0                    # Initialize the total variable
    for i in range(len(lst)):  # Loop over the elements of the list
        total=total+lst[i]     # Add values to total
    lst_av=total/len(lst)      # Divide total by len(lst)

    for i in range(len(lst)):  # Loop over the elements of the list
        lst[i]/=lst_av         # Divide

    return lst                 # Return the result


start_seq = [20, 24, 28, 29, 300, 560, 578]
print(norm_lst(start_seq))

[0.09096816114359974, 0.10916179337231968, 0.12735542560103963, 0.13190383365821962, 1.364522417153996, 2.5471085120207926, 2.6289798570500325]


We named a variable `list_` to avoid overwriting the built-in `list`.

The same code but with better comments.

In [84]:
def norm_lst(list_):
    """Return a normalized list of numbers with mean 1"""
    lst = list_.copy()

    # Compute the mean
    total = 0
    for i in range(len(lst)):
        total = total + lst[i]
    lst_av = total / len(lst)

    # Normalize
    for i in range(len(lst)):
        lst[i] /= lst_av

    return lst


print(norm_lst(start_seq))

[0.09096816114359974, 0.10916179337231968, 0.12735542560103963, 0.13190383365821962, 1.364522417153996, 2.5471085120207926, 2.6289798570500325]


Good naming and clear code means comments might not be needed.

In [ ]:
def normalize_list_by_mean(list_):
    """Return a normalized list of numbers with mean 1"""
    mean = sum(list_) / len(list_)
    return [elem / mean for elem in list_]


print(normalize_list_by_mean(start_seq))


# Absolute and relative paths

**Path** is a string that specifies the location of a file in the file system hierarchy.

**Absolute path** specifies the location independently of the current working directory.

**Relative path** specifies the location relative to the current working directory.

For example, if this notebook were located in `/home/username/Documents/course/project/` and the directory also contained a subdirectory `data/` with the file `input1.csv` then the absolute path to that file would be `/home/username/Documents/course/project/data/input1.csv` and the relative path would be `data/input1.csv`.

**NB! The path separator is OS-dependent: "/" on Unix-like systems, "\\" on Windows!**

In [40]:
from pathlib import Path

print(Path("data", "input1.csv"))            # Relative path
print(Path("data", "input1.csv").resolve())  # Absolute path

data/input1.csv
/Users/isabellah/Desktop/Python Course/Lecture 1/data/input1.csv



### PEP-8

[PEP-8](https://www.python.org/dev/peps/pep-0008/) is the Python style guide.

It gives recommendations for things like:

- **Indentation** – how far code is moved in
- **Spaces** – where to use spaces in your code
- **Variable names** – how to name variables clearly
- **Line length** – avoid very long lines
- **Code organization** – keep your code structured and readable

The Python interpreter does not require you to follow PEP-8. Your code can still run without it.

**But following PEP-8 makes your code easier for people and tools to read.**

## These topics (and more) is available in greater detail in the accompanying manual notebook!

# www.menti.com code: xxxx xxxx

### Exit question 1: Mark which things below are sequences

$\quad$<b>A)</b> `[1, 2, 3]`<br>
$\quad$<b>B)</b> `(1, 2, 3)`<br>
$\quad$<b>C)</b> `'123'`<br>
$\quad$<b>D)</b> `1.23`

Correct answer: A & B & C

### Exit question 2: What does the following block return?

```python
def add_five(a, b):
    return a+5, b+5

result = add_five(3, 2)
print(result)
```

$\quad$<b>A)</b> 5<br>
$\quad$<b>B)</b> 15<br>
$\quad$<b>C)</b> (8, 7)<br>
$\quad$<b>D)</b> `SyntaxError`

Correct answer: C

### Exit question 3: Mark the correct statements.

$\quad$<b>A)</b> Arithmetic expressions can include ints and floats together.<br>
$\quad$<b>B)</b> All strings must be declared with single quotation marks ( ' )<br>
$\quad$<b>C)</b> PEP-8 is the Python definition. Adherence is required for the code to work.<br>
$\quad$<b>D)</b> The first element of a sequence is always 0.

Correct answer: A

# Now it's time to use the manual to solve the exercises.